Branks42  606  Answer Checking
eikonomega/django-workflow-system pull request #87
Opened 2021-06-04 01:09 UTC by branks42

***Work Completed***
- Created Response Schema functions for all prepopulated question types
- Wiped and rebooted all migrations
- Updated migration which includes all question types included with package
- __function_table on WorkflowStepUserInput that will populate based on directories defined in settings under `RESPONSE_SCHEMA_HANDLERS`
- Update tests

***Steps Required***
- New initial migration.

2021-06-08 20:16 UTC, eikonomega requested changes
I have some more files to review... but will have to get back to that tomorrow morning. :)

2021-06-08 20:16 UTC, eikonomega commented on .gitignore
> +eggsellent/*
LOL... did you want this here?

2021-06-08 20:16 UTC, eikonomega commented on django_workflow_system/migrations/0002_auto_20210603_1925.py
> +# Generated by Django 3.1.8 on 2021-06-04 00:25
Since this isn't *really* an auto-generated migration, how about we change the name to make it's purpose a little clearer?

`0002_create_standard_user_input_types.py` or something like that?

2021-06-08 20:16 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +from django_workflow_system.utils.response_schema_handlers.single_choice_question import get_response_schema as single_choice_question_schema
Looks like it would be helpful to create some convenience imports in `django_workflow_system.utils.response_schema_handlers` to clean this up...

2021-06-08 20:16 UTC, eikonomega commented on test_project/settings.py
> +RESPONSE_SCHEMA_HANDLERS = []
Can we use a dictionary here to namespace the settings? 

Like so... just like DRF does it! :) 

```
DJANGO_WORKFLOW_SYSTEM = {
    INPUT_TYPE_RESPONSE_SCHEMA_HANDLERS = []
}
```

Also, it should be optional to supply these. You may already have that and I just haven't gotten that far yet.

2021-06-08 20:16 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
>  from jsonschema import Draft7Validator, SchemaError
Looks like these aren't used anymore here?

2021-06-08 20:16 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +    def _load_function_table(cls):
Looks like this probably doesn't need to be a `@classmethod` since it is just called from another method of the class...

I could be missing something, but generally class methods are used when you want to utilize a specific aspect of a class from outside the class without instantiating an object.

2021-06-08 20:16 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/single_choice_question.py
> +    elif not instance.specification['meta']['inputRequired'] and instance.specification['meta']['correctInputRequired']:
Oh this is an interesting combination...

Ideally, in the JSON Schema for the type we would be able to preclude this situation from arising.
If you have `correctInputRequired` you MUST also have `inputRequired` in the schema. Could you do a quick look-see to see if that is currently possible?

2021-06-08 20:16 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/single_choice_question.py
> +
Need a docstring for the module as a whole...

Perhaps `Response Schema Generator Module`?

2021-06-09 12:13 UTC, branks42 commented on .gitignore
> +eggsellent/*
I think I'm gonna leave it. This was how I was testing the user defined response_schema imports

2021-06-09 12:16 UTC, branks42 commented on django_workflow_system/migrations/0002_auto_20210603_1925.py
> +# Generated by Django 3.1.8 on 2021-06-04 00:25
👍🏼

2021-06-09 12:20 UTC, branks42 commented on django_workflow_system/models/step_user_input.py
>  from jsonschema import Draft7Validator, SchemaError
👍🏼

2021-06-09 12:29 UTC, branks42 commented on django_workflow_system/models/step_user_input.py
> +    def _load_function_table(cls):
You are correct, thank you

2021-06-09 12:49 UTC, branks42 commented on django_workflow_system/utils/response_schema_handlers/single_choice_question.py
> +    elif not instance.specification['meta']['inputRequired'] and instance.specification['meta']['correctInputRequired']:
Good catch

2021-06-09 13:47 UTC, branks42 commented on test_project/settings.py
> +RESPONSE_SCHEMA_HANDLERS = []
It is optional :)

2021-06-09 15:24 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +from django_workflow_system.utils.response_schema_handlers import (
It looks like Black is not automatically formatting for you... :( 
We should take a look and see what is the cause of that.

2021-06-09 15:27 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +        # Need to ensure that if correctInput is true, thatt inputRequired is also true.
`thatt` -> `that` :)

2021-06-09 15:33 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +            if 'correctInputRequired' in self.specification['meta'].keys() and 'inputRequired' in self.specification['meta'].keys():
If you want, you could also do 
```
if set(['correctInputRequired', 'inputRequired']).issubset(self.specification['meta'].keys())
```

2021-06-09 15:33 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +            if 'correctInputRequired' in self.specification['meta'].keys() and 'inputRequired' in self.specification['meta'].keys():
It's sort of meant for subset checking...

2021-06-09 18:19 UTC, eikonomega commented on django_workflow_system/models/step_user_input.py
> +        """
`cls` -> `self` 
It is just a regular method now.

2021-06-09 18:19 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/__init__.py
> +from .date_range_question import get_response_schema as date_range_question_schema
So nice.

2021-06-09 18:24 UTC, branks42 commented on django_workflow_system/models/step_user_input.py
> +        """
D'oh! Good catch

2021-06-09 18:27 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/date_range_question.py
> +    response_schema = {
Looks like this initial setup is a CONSTANT? 
Maybe define this in the `__init__.py` and just create a copy in each method and modify it?

2021-06-09 18:31 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/date_range_question.py
> +def add_years(d, years):
Variable named `d`... how about we update that? :)

2021-06-09 18:31 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/date_range_question.py
> +def add_years(d, years):
Also, let's use Google Style Docstrings? There is a plugin that makes these easy for VSCode. We can go over that tomorrow.

2021-06-09 20:22 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/date_range_question.py
> +def fetch_all_possible_dates(instance):
Uh... this makes my head hurt. Thank you for doing it!
Do we have some unit tests around this?

2021-06-09 20:27 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/multiple_choice_question.py
> +def get_response_schema(instance):
`instance` seems a little vague...

2021-06-09 20:30 UTC, eikonomega commented on django_workflow_system/utils/response_schema_handlers/multiple_choice_question.py
> +    all_combos = []
Would it be possible to use the JSON Schema `anyOf` directive here?

2021-06-09 20:36 UTC, eikonomega requested changes
Here are some more comments. :)

2021-06-09 23:54 UTC, branks42 commented on django_workflow_system/utils/response_schema_handlers/multiple_choice_question.py
> +    all_combos = []
I don't think so, unfortunately. We can use the anyOf to declare type, but not options.

2021-06-11 13:59 UTC, merged